name: diapason
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.3
  test: ^1.16.5
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  firebase_storage: ^8.0.5
  firebase_messaging: ^9.1.3
  curved_navigation_bar: ^0.3.4
  timeline_tile: ^1.0.0
  modal_progress_hud: ^0.1.3
  image_picker: ^0.7.4
  cached_network_image: ^2.4.1
  intl: ^0.17.0
  font_awesome_flutter: ^8.10.0
  material_design_icons_flutter: ^4.0.5755
  flutter_animation_progress_bar: ^1.0.6
  url_launcher: ^6.0.3
  geocoder: ^0.2.1
  flutter_google_places: ^0.2.6
  google_maps_webservice: ^0.0.18
  google_fonts: ^2.0.0
  uuid: ^3.0.4
  http: ^0.13.3
  provider: ^4.3.3
  carousel_slider: ^3.0.0
  flutter_slidable: ^0.5.7
  multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  auto_size_text: ^2.1.0
  flutter_staggered_grid_view: ^0.3.4




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - images/
